# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('subheader', models.CharField(blank=True, max_length=255)),
                ('section_one_title', models.CharField(default='', max_length=255)),
                ('section_one_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_one_item_one_title', models.CharField(default='', max_length=255)),
                ('section_one_item_one_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_one_item_two_title', models.CharField(default='', max_length=255)),
                ('section_one_item_two_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_one_item_three_title', models.CharField(default='', max_length=255)),
                ('section_one_item_three_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_two_title', models.CharField(default='', max_length=255)),
                ('section_two_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_two_item_one_title', models.CharField(default='', max_length=255)),
                ('section_two_item_one_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_two_item_two_title', models.CharField(default='', max_length=255)),
                ('section_two_item_two_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_two_item_three_title', models.CharField(default='', max_length=255)),
                ('section_two_item_three_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_two_item_four_title', models.CharField(default='', max_length=255)),
                ('section_two_item_four_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_two_item_five_title', models.CharField(default='', max_length=255)),
                ('section_two_item_five_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_two_item_six_title', models.CharField(default='', max_length=255)),
                ('section_two_item_six_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('section_three_title', models.CharField(default='', max_length=255)),
                ('section_three_body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', hitcount.models.HitCountMixin),
        ),
    ]
