# Generated by Django 2.0.8 on 2018-08-18 15:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('subheader', models.CharField(blank=True, max_length=255)),
                ('section_one_title', models.CharField(default='', max_length=255)),
                ('section_one_body', wagtail.core.fields.RichTextField(blank=True)),
                ('section_one_item_one_title', models.CharField(default='', max_length=255)),
                ('section_one_item_one_body', wagtail.core.fields.RichTextField(blank=True)),
                ('section_one_item_two_title', models.CharField(default='', max_length=255)),
                ('section_one_item_two_body', wagtail.core.fields.RichTextField(blank=True)),
                ('section_one_item_three_title', models.CharField(default='', max_length=255)),
                ('section_one_item_three_body', wagtail.core.fields.RichTextField(blank=True)),
                ('section_two_title', models.CharField(default='', max_length=255)),
                ('section_two_body', wagtail.core.fields.RichTextField(blank=True)),
                ('section_three_title', models.CharField(default='', max_length=255)),
                ('section_three_body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('subheader', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecipesIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecipesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
