# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('subheader', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_five_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_five_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_four_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_four_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_one_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_one_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_six_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_six_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_three_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_three_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_two_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_two_item_two_title',
        ),
    ]
