# Generated by Django 2.0.5 on 2018-05-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
