# Generated by Django 2.0.5 on 2018-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180518_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='header1',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='header2',
            new_name='subheader',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_body',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_item_one_body',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_item_one_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_item_three_body',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_item_three_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_item_two_body',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_item_two_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
