# Generated by Django 2.0.5 on 2018-05-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180521_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='section_three_body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_three_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
