# Generated by Django 2.0.5 on 2018-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180522_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subheader',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
